# Generated by Django 3.0.4 on 2020-04-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200320_0409'),
    ]

    operations = [
        migrations.AddField(
            model_name='handledcall',
            name='delivered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
