# Generated by Django 3.0.4 on 2020-04-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_handledcall_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handledcall',
            name='handled_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
