# Generated by Django 3.0.4 on 2020-04-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200405_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='handledcall',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
