# Generated by Django 3.0.4 on 2020-04-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_handledcall_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handledcall',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='handledcall',
            name='delivered_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='handledcall',
            name='handled_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
