# Generated by Django 3.0.4 on 2020-04-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200405_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HandledCall',
            new_name='Call',
        ),
    ]
