# Generated by Django 3.0.4 on 2020-04-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200408_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='call',
            name='recording_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
